export default {
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Product Name',
      type: 'string',
    },
    {
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
      description:
        'This is crucial. It generates the custom URL (e.g., the-vantage). Click generate after typing the name.',
    },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          {title: 'Settees & Sofas', value: 'settees-sofas'},
          {title: 'Accent Seating', value: 'accent-seating'},
          {title: 'Daybeds & Benches', value: 'daybeds-benches'},
          {title: 'The Modular Experiences', value: 'the-modular-experience'},
          {title: 'Consoles', value: 'consoles'},
          {title: 'Center Tables', value: 'center-tables'},
          {title: 'Accent Tables', value: 'accent-tables'},
          {title: 'Writing Desks', value: 'writing-desks'},
          {title: 'Gathering Tables', value: 'gathering-tables'},
          {title: 'Dining Seating', value: 'dining-seating'},
          {title: 'Buffets', value: 'buffets'},
          {title: 'Indoor Flora', value: 'indoor-flora'},
          {title: 'Tabletop', value: 'tabletop'},
          {title: 'Miroirs', value: 'miroirs'},
          {title: 'Bedsteads', value: 'bedsteads'},
          {title: 'Night Tables', value: 'night-tables'},
          {title: 'Fine Cabinetry', value: 'fine-cabinetry'},
          {title: 'Ambient Lighting', value: 'ambient-lighting'},
          {title: 'Fine Art', value: 'fine-art'},
          {title: 'Floor Coverings', value: 'floor-coverings'},
          {title: 'Modernist Restraint', value: 'modernist-restraint'},
          {title: 'Nomadic Elegance', value: 'nomadic-elegance'},
          {title: 'Quiet Luxury', value: 'quiet-luxury'},
          {title: 'Spring/Summer26', value: 'spring/summer26'},
          {title: 'Autumn/Winter26', value: 'autumn/winter26'},
          {title: 'Signature Pieces', value: 'signature-pieces'},
        ],
        layout: 'dropdown',
      },
    },
    {
      name: 'price',
      title: 'Price (USD)',
      type: 'number',
    },
    {
      name: 'materials',
      title: 'Materials',
      type: 'string',
    },
    {
      name: 'dimensions',
      title: 'Dimensions',
      type: 'string',
    },
    {
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
    },
    {
      name: 'detailedDescription',
      title: 'Detailed Description',
      type: 'text',
    },
    {
      name: 'mainImage',
      title: 'Main Photo (Hero/Thumbnail)',
      type: 'image',
      options: {hotspot: true},
    },
    {
      name: 'gallery',
      title: 'Photo Gallery (For Product Details)',
      type: 'array',
      of: [{type: 'image', options: {hotspot: true}}],
    },
  ],
}
